version: '3.8'
services:
  api:
    container_name: api
    build:
      context: .
    volumes:
      - .:/src/api
      - /src/api/node_modules
    ports:
      - 3000:3000
    command: ["npm", "start"]
