version: '3.8'
services:
  api:
    container_name: api
    build:
      context: .
    volumes:
      - .:/src/api
      - /src/api/node_modules
    ports:
      - 4000:4000
    command: [ "npm", "start" ]
